# Generated by Django 5.0.7 on 2024-10-20 11:16

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("loyalty_points", models.PositiveIntegerField(default=0)),
                ("joined_date", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(default="", max_length=15)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                ("hire_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ExpenseReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RevenueReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("total_revenue", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_profit", models.DecimalField(decimal_places=2, max_digits=12)),
                ("details", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact_person", models.CharField(max_length=255)),
                (
                    "address",
                    models.CharField(
                        default="123 Supplier St, Supplier City, Supplier Country",
                        max_length=255,
                    ),
                ),
                ("phone", models.CharField(default="", max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("delivery_times", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=10)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("barcode", models.CharField(max_length=13, unique=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("restock_date", models.DateField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="core.category",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="core.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(default=django.utils.timezone.now)),
                ("total_sales", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_profit", models.DecimalField(decimal_places=2, max_digits=12)),
                ("metrics", models.TextField(blank=True, null=True)),
                ("insights", models.TextField(blank=True, null=True)),
                (
                    "top_customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_customer",
                        to="core.customer",
                    ),
                ),
                (
                    "top_selling_product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_selling_product",
                        to="core.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="core.employee",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="shift_schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="core.shift",
            ),
        ),
    ]
