# Generated by Django 5.0.7 on 2024-10-20 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_product_stock_employee_assigned_shifts_and_more"),
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="core.product",
            ),
        ),
    ]
